### PR TITLE
feat: Bump Decidim v0.26.8 and add module custom proposals state

### PR DESCRIPTION
**Pull request by alecslupu**
#### Description 

- [x] Bump Decidim version to 0.26.8
- [x] Add module custom proposals state

### CODE REVIEW

**Review by Quentinchampenois — CHANGES_REQUESTED** [review]
Thank you for you PR and this module ! 

I have few asks :
* Can you add in your PR the module's migrations please ? 

Also, seed does not work because of unexpected return in the module's engine, see stacktrace : 

```
rake aborted!
LocalJumpError: unexpected return
/Users/USER/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/bundler/gems/decidim-module-custom_proposal_states-002e454edc6d/lib/decidim/custom_proposal_states/engine.rb:52:in `block (2 levels) in <class:Engine>'
```
Related to this block of code :

```
 51         Rails.application.reloader.to_prepare do
 52           return unless Decidim.module_installed?("elections")
 53
 54           Decidim::Elections::Admin::ImportProposalsToElections.prepend Decidim::CustomProposalStates::Overrides::ImportProposalsToElections
 55         end
```
Do you ever encounter this error ? 

Fyi, I can't generate the development_app on module because seeds fail with `ActiveModel::UnknownAttributeError: unknown attribute 'state' for Decidim::Proposals::Proposal.`

**Comment by alecslupu** [comment]
hello  @Quentinchampenois all the issues reported should be fixed. Can u provide some feeback ?
cc @simonaszilinskas

**Comment by simonaszilinskas** [comment]
@moustachu do you think we can put it on the staging?

**Review by moustachu — APPROVED** [review]

**Comment by Quentinchampenois** [comment]
Hello, sorry for the delay 

I tested it locally, it runs now, I just have some requests : 

- In the BO, as a administrator : When I create a new state, If I don't fill the `token` field and save, I have a success flash message but state isn't persisted 
- In this application decidim-nyc, If I navigate to proposal answer form in the BO, I have an internal server error 
```
undefined local variable or method available_states for #‹#Class: 0×0000000151615fd8>: 0×000000013148ba48>
Did you mean? available_locales
@available_locales
decidim-proposals (0.26.7) app/views/decidim/proposals/admin/proposal_answers/_form.html.erb:10
actionview (6.0.6.1) lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
actionview (6.0.6.1) lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
actionview (6.0.6.1) lib/action_view/helpers/capture_helper.rb:45:in `capture'
actionview (6.0.6.1) lib/action_view/helpers/form_helper.rb:452:in `form_for'
decidim-core (0.26.7) app/helpers/decidim/decidim_form_helper.rb:34:in `decidim_form_for'
decidim-proposals (0.26.7) app/views/decidim/proposals/admin/proposal_answers/_form.html.erb:1
actionview (6.0.6.1) lib/action_view/base.rb:274:in `_run'
actionview (6.0.6.1) lib/action_view/template.rb:185:in `block in render'
activesupport (6.0.6.1) lib/active_support/notifications.rb:182:in `instrument'
actionview (6.0.6.1) lib/action_view/template.rb:385:in `instrument_render_template'
actionview (6.0.6.1) lib/action_view/template.rb:183:in `render'
actionview (6.0.6.1) lib/action_view/renderer/partial_renderer.rb:357:in `block in render_partial'
actionview (6.0.6.1) lib/action_view/renderer/abstract_renderer.rb:88:in `block in instrument'
activesupport (6.0.6.1) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.6.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.6.1) lib/active_support/notifications.rb:180:in `instrument'
actionview (6.0.6.1) lib/action_view/renderer/abstract_renderer.rb:87:in `instrument'
```
- Just a question, does the 0.26.8 is still needed in this PR ? I can see that application is still in 0.26.7 for now

Thank you and I remain available if needed !

**Comment by alecslupu** [comment]
> Hello, sorry for the delay
> 
> I tested it locally, it runs now, I just have some requests :
> 
>     * In the BO, as a administrator : When I create a new state, If I don't fill the `token` field and save, I have a success flash message but state isn't persisted
> 
>     * In this application decidim-nyc, If I navigate to proposal answer form in the BO, I have an internal server error
> 
> 
> ```
> undefined local variable or method available_states for #‹#Class: 0×0000000151615fd8>: 0×000000013148ba48>
> Did you mean? available_locales
> @available_locales
> decidim-proposals (0.26.7) app/views/decidim/proposals/admin/proposal_answers/_form.html.erb:10
> actionview (6.0.6.1) lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
> actionview (6.0.6.1) lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
> actionview (6.0.6.1) lib/action_view/helpers/capture_helper.rb:45:in `capture'
> actionview (6.0.6.1) lib/action_view/helpers/form_helper.rb:452:in `form_for'
> decidim-core (0.26.7) app/helpers/decidim/decidim_form_helper.rb:34:in `decidim_form_for'
> decidim-proposals (0.26.7) app/views/decidim/proposals/admin/proposal_answers/_form.html.erb:1
> actionview (6.0.6.1) lib/action_view/base.rb:274:in `_run'
> actionview (6.0.6.1) lib/action_view/template.rb:185:in `block in render'
> activesupport (6.0.6.1) lib/active_support/notifications.rb:182:in `instrument'
> actionview (6.0.6.1) lib/action_view/template.rb:385:in `instrument_render_template'
> actionview (6.0.6.1) lib/action_view/template.rb:183:in `render'
> actionview (6.0.6.1) lib/action_view/renderer/partial_renderer.rb:357:in `block in render_partial'
> actionview (6.0.6.1) lib/action_view/renderer/abstract_renderer.rb:88:in `block in instrument'
> activesupport (6.0.6.1) lib/active_support/notifications.rb:180:in `block in instrument'
> activesupport (6.0.6.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
> activesupport (6.0.6.1) lib/active_support/notifications.rb:180:in `instrument'
> actionview (6.0.6.1) lib/action_view/renderer/abstract_renderer.rb:87:in `instrument'
> ```
> 
>     * Just a question, does the 0.26.8 is still needed in this PR ? I can see that application is still in 0.26.7 for now
> 
> 
> Thank you and I remain available if needed !

@Quentinchampenois 
1. I will need to investigate. 
2. You would need to restart your dev server ( i had this problema and there is a spec covering this ... so, techwize seems ok) 
3. Regarding the decidim version, we are working on releasing 0.26.9 ( most likely tomorrow )

**Comment by alecslupu** [comment]
closing in favour of  #92

**Pull request closed without merging**
